// PRODUCT NAME
export const ADD_PRODUCT_NAME = "CREATE_PRODUCT_NAME";
export const EDIT_PRODUCT_NAME = "EDIT_PRODUCT_NAME";
export const GET_PRODUCT_NAMES = "GET_PRODUCT_NAMES";
export const PRODUCT_NAME_LOADING = "PRODUCT_NAME_LOADING";
export const DELETE_PRODUCT_NAME = "DELETE_PRODUCT_NAME";

// VENDOR
export const ADD_VENDOR = "ADD_VENDOR";
export const GET_VENDORS = "GET_VENDORS";
export const RESET_NEW_VENDOR_ID = "RESET_NEW_VENDOR_ID"
export const VENDOR_LOADING = "VENDOR_LOADING";
export const VENDOR_MODAL_OPEN = "VENDOR_MODAL_OPEN";
export const VENDOR_MODAL_CLOSE = "VENDOR_MODAL_CLOSE";